### ISSUE TITLE
Fix typo with the gif command

### ISSUE THREAD

**Issue by banner4422** [thebentobot/bento-web-legacy#6]

**Comment by Jayita10** [comment]
Can I work on this issue?

**Comment by banner4422** [comment]
I didn't expect any contributors, hello! 👀

As I wrote in my readme, pull requests are very welcome if the features/changes makes sense and are up to par in quality. 

The thing about this issue though is that it is just a typing (perhaps grammatical) mistake that needs to be corrected at some point. I won't do it right now because I'm planning to take a break, but if you really want to fix this very simple thing, you're of course welcome.

- It's a mistake which can be seen in the description of this div on the site [here](https://bentobot.xyz/commands#gif)
- All it takes is to replace the string [on line 181 in ./util/commandsJSONList.ts](https://github.com/thebentobot/bento-web/blob/master/util/commandsJSONList.ts#L181) with "Searches for a random GIF based on the search input. The GIF comes from Tenor which has a g-rated content filter for non-NSFW channels. The filter is off in NSFW channels."

If you want to, I would really appreciate it and thank you for reaching out. But yeah as you can see, there isn't that much ''bite'' to this issue, so it's totally fine and understandable if you don't want to 😅 It's my bad for not elaborating on the issue and just treating it as my todo. My future issues will include a description, and yeah I will remember it's a public forum from now on.

**Comment by Jayita10** [comment]
It's okay. I am new to open source and exploring it. I wouldn't mind fix this typo :)
